#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Official Website: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

Messages:
  Title:
    # Message sent before login
    before-login:
      title: "&a&lBEM-VINDO!"
      subtitle: "&7Utilize: /login <sua palavra-passe>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent before registration
    before-register:
      title: "&a&lBEM-VINDO!"
      subtitle: "&7Utilize: /register <sua palavra-passe> <sua palavra-passe>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent after login
    after-login:
      title: ""
      subtitle: "&aIniciou sessão com sucesso!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent after register
    after-register:
      title: ""
      subtitle: "&aRegistou-se com sucesso!"
      delays:
        start: 0
        duration: 60
        end: 6

  delay-kick:
    # Message sent when a user takes a long time to register
    register-kick: "&cLevou imenso tempo a registar-se."

    # Message sent when a user takes a long time to log in
    login-kick: "&cLevou imenso tempo a iniciar sessão."

  successful-operations:
    # Message when a user exchanges their password
    password-changed: "&aA sua palavra-passe foi alterada com sucesso."

    # Message sent when a user successfully logs
    successful-login: "&aIniciou sessão com sucesso."

    # Message sent when a user successfully registers
    successful-register: "&aRegistou-se com sucesso."

    # Message sent when a player successfully disregisters
    unregister-kick: "&cDesregistou-se com sucesso."

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname
    nick-already-registered: "&cNão pode entrar com o nome {0}&r\n&r&cEste nome já foi registado como {1}&r\n&r\n&r&cPara entrar, deve usar o seu nome sem maiúsculas / minúsculas."

    # Message sent when a user misses many times
    failed-many-times: "&cIntroduziu a palavra-passe incorrecta."

    # Message sent when password entered is incorrect
    incorrect-password: "&cPalavra-passe incorrecta. Por favor, tente novamente."

    # Message sent when a player enters an invalid nickname.
    invalid-nickname: "&cDesculpe, mas está a usar um nome inválido."

  error-messages:
    # Message sent when you are already logged in.
    already-login: "&cJá tem sessão iniciada."

    # Message sent when a nickname has already been registered.
    already-registered: "&cEste nome já foi registado."

    # Message sent when a nickname has not yet been registered.
    not-registered: "&cEste nome ainda não foi registado."

    # Message sent when the entered password is not equal to the second
    passwords-dont-match: "&cAs palavras-passe não coincidem."

    # Message sent when a player tries to change password by entering the same password as the current
    password-same-as-old: "&cA palavra-passe introduzida é a mesma que a atual."

    # Message sent when the password entered is too large
    password-too-large: "&cA palavra-passe introduzida é demasiado grande."

    # Message sent when the password entered is too small
    password-too-small: "&cA palavra-passe introduzida é demasiado pequena."

    # Message when a player does not possess the required permission
    insufficient-permissions: "&cNão tem permissão para operar este comando."

    # Message to kick a player now online
    already-online: "&cEste jogador já está disponível."

    # Message to show that the command cannot be executed via console
    player-command-usage: "&cEste comando foi desactivado através do terminal."

    # Message shown when the plugin is reloaded.
    plugin-reload-message: "&eO plugin foi recarregado com sucesso."

    # Message sent when a database operation has not been successfully performed
    database-error: "&cLamentamos, mas não fomos capazes de concluir esta operação. Por favor, tente novamente. [FALHA NO SQL]"

  other-messages:
    # Mensagem enviada para o uso do comando /logar
    message-login: "&eUtilize o comando /login <palavra-passe>"

    # Mensagem enviada para o uso do comando /register
    message-register: "&eUtilize o comando /register <palavra-passe> <palavra-passe>"

    # Mensagem enviada para o uso do comando /mudarsenha
    message-changepassword: "&eUtilize o comando /changepassword <palavra-passe atual> <nova palavra-passe>"

    # Message sent to use the /unregister command
    message-unregister: "&eUtilize o comando /unregister <palavra-passe atual>"